system "D:\\BioTMFullversion\\Single_article_mode\\Stop_word_cancel_Frame.pl";
system "D:\\BioTMFullversion\\Single_article_mode\\All_upper_case_Frame.pl";
system "D:\\BioTMFullversion\\Single_article_mode\\cross_diseases_databace_Frame.pl";
system "D:\\BioTMFullversion\\Single_article_mode\\cross_gene_databace_Frame.pl";
system "D:\\BioTMFullversion\\Single_article_mode\\word_counting_Frame.pl";
system "D:\\BioTMFullversion\\Single_article_mode\\Frame.html";

